### ISSUE TITLE
Support for set-dst

### ISSUE THREAD

**Issue by davidmogar** [haproxytech/client-native#1]
After a talk with @bedis we concluded that support for this option is needed for my use case.

What I'm trying to achieve is to be able to have header based routing in the HAProxy Ingress controller and for that I would have a config similar to the next one:
```
resolvers dns
    hold nx 3s
    hold obsolete 0s
    hold other 3s
    hold valid 10s
    parse-resolv-conf
    timeout retry 10s

frontend frontend-host-traffic
    bind :8140 ssl crt /cert ca-file /ca verify required no-sslv3 v4v6
    default_backend backend-host-traffic
    
    http-request set-var(sess.namespace) hdr(X-Namespace)
    http-request set-var(sess.service) hdr(X-Service)
    http-request do-resolve(txn.service,dns,ipv4) str(),concat(,sess.service,.),concat(,sess.namespace,.svc.cluster.local)
    
    http-request set-header X-Client-Verify-Real %[ssl_c_verify]
    http-request set-header X-Client-Verify NONE if !{ hdr_val(X-Client-Verify-Real) eq 0 }
    http-request set-header X-Client-Verify SUCCESS if { hdr_val(X-Client-Verify-Real) eq 0 }
    http-request set-header X-Client-DN CN=%{+Q}[ssl_c_s_dn(cn)]
    
    http-request deny if { method PUT POST } { hdr_val(Content-length) ge 62914560 }

backend backend-host-traffic
    http-request set-dst var(txn.service)
    http-request set-dst-port int(8140)
    server service 0.0.0.0:0
```
Most of the options are supported but this specific one is not. Let me know if I can be of any help!

**Comment by mjuraga** [comment]
If you are interested in adding those options yourself, you should 

1. Add them in [config-parser](https://github.com/haproxytech/config-parser) package, specifically by adding them [here](https://github.com/haproxytech/config-parser/blob/master/parsers/http/http-request.go#L47) and adding new appropriate actions (you should look at the existing ones).
2. Once the parser can parse those options add them to the specification yaml in the [dataplaneapi-specification project]( https://github.com/haproxytech/dataplaneapi-specification/blob/master/models/haproxy.yaml#L510)
3. Generate new [models](https://github.com/haproxytech/models) package
4. Add new options [here](https://github.com/haproxytech/client-native/blob/master/configuration/http_request_rule.go)

If you get stuck during the process I'll be happy to provide more guidance, and if you do not have the time to add those options, we'll definitely put it in our roadmap.

**Comment by bedis** [comment]
+1 :)

**Comment by davidmogar** [comment]
As said, happy to help. I'll give it a try. Going on holidays though so... eventually ;)

**Comment by oktalz** [comment]
commit 02c45170 added do-resolve, set-dst, set-dst-port
