### ISSUE TITLE
Unable to initialise the haproxy go client

### ISSUE THREAD

**Issue by glaceroy** [haproxytech/client-native#41]
I am running the below code in Minishift v3.11 but unable to initialise the configuration client and getting the below error

# Errors

./haproxy-main.go:42:17: undefined: configuration
./haproxy-main.go:43:16: undefined: configuration
./haproxy-main.go:54:25: undefined: configuration
./haproxy-main.go:57:11: undefined: api
./haproxy-main.go:61:20: undefined: runtime_api
./haproxy-main.go:73:16: too many arguments to return
	have (nil)
	want ()
./haproxy-main.go:87:15: undefined: h
./haproxy-main.go:87:50: undefined: t

# My code
*******************************
package main

import (
        "log"
        "fmt"
        corev1client "k8s.io/client-go/kubernetes/typed/core/v1"
        "k8s.io/client-go/tools/clientcmd"
	"github.com/haproxytech/client-native"
)

func main() {

        // Instantiate loader for kubeconfig file.
        kubeconfig := clientcmd.NewNonInteractiveDeferredLoadingClientConfig(
                clientcmd.NewDefaultClientConfigLoadingRules(),
                &clientcmd.ConfigOverrides{},
        )

        // Determine the Namespace referenced by the current context in the
        // kubeconfig file.
        namespace, _, err := kubeconfig.Namespace()
        if err != nil {
                log.Fatal(err)
        }
        
        // Get a rest.Config from the kubeconfig file.  This will be passed into all
        // the client objects we create.
        restconfig, err := kubeconfig.ClientConfig()
        if err != nil {
                log.Fatal(err)
        }

        // Create a Kubernetes core/v1 client.
        coreclient, err := corev1client.NewForConfig(restconfig)
        if err != nil {
                log.Fatal(err)
        }

	// Haproxy client
	confClient := &configuration.Client{}
	confParams := configuration.ClientParams{
    		ConfigurationFile:      "/etc/haproxy/haproxy.cfg",
    		Haproxy:                "/usr/sbin/haproxy",
    		UseValidation:          true,
    		PersistentTransactions: true,
    		TransactionDir:         "/tmp/haproxy",
	}

	err = confClient.Init(confParams)
	if err != nil {
    		fmt.Println("Error setting up configuration client, using default one")
    		confClient, err = configuration.DefaultClient()
    		if err != nil {
       			fmt.Println("Error setting up default configuration client, exiting...")
        		api.ServerShutdown()
    		}
	}

	runtimeClient := &runtime_api.Client{}
	globalConf, err := confClient.GetGlobalConfiguration("")
	if err == nil {
    		socketList := make([]string, 0, 1)
    		runtimeAPIs := globalConf.Data.RuntimeApis

    		if len(runtimeAPIs) != 0 {
        		for _, r := range runtimeAPIs {
            			socketList = append(socketList, *r.Address)
        		}
        		if err := runtimeClient.Init(socketList, "", 0); err != nil {
            			fmt.Println("Error setting up runtime client, not using one")
            			return nil
				}
   		} else {
			fmt.Println("Runtime API not configured, not using it")
			runtimeClient = nil
		}
	} else {
    		fmt.Println("Cannot read runtime API configuration, not using it")
    		runtimeClient = nil
	}

	client := &client_native.HAProxyClient{}
	client.Init(confClient, runtimeClient)

	bcks, err := h.Client.Configuration.GetBackends(t)
	if err != nil {
    		fmt.Println(err.Error())
	}

	backendsJSON, err := bcks.MarshallBinary()

	if err != nil {
    		fmt.Println(err.Error())
	}
	fmt.Println(string(backendsJSON))
}

**Comment by glaceroy** [comment]
While trying to download runtime package getting the below error
 package github.com/haproxytech/client-native/v2/runtime: cannot find package "github.com/haproxytech/client-native/v2/runtime" in any of:
	/usr/local/Cellar/go/1.13.1/libexec/src/github.com/haproxytech/client-native/v2/runtime (from $GOROOT)
	/Users/xxxx/go/src/github.com/haproxytech/client-native/v2/runtime (from $GOPATH)

**Comment by oktalz** [comment]
hi @glaceroy 

it seems that are missing few imports (just an example)
"github.com/haproxytech/client-native/v2"
"github.com/haproxytech/client-native/v2/configuration"
"github.com/haproxytech/client-native/v2/runtime"

as a help you can see how its initialized in [dataplane](https://github.com/haproxytech/dataplaneapi/blob/8f2c052832cc266835559c32f4821626be3f6ab9/configure_data_plane.go) or in [k8s ingress controller](https://github.com/haproxytech/kubernetes-ingress/blob/master/controller/haproxy/api/api.go#L64)

**Comment by MartijnStraatman** [comment]
Hi, just found this post. We are planning some kind of operator which will query ingresses in our k8s-cluster. If found we are planning to add a frontend to the haproxy running outside the cluster. Is this possible with the client-native?  I am trying to figure out how we can communicate with the haproxy through the client-native. I don't see any endpoints configured. Or do we need to communicate with the rest-api directly? If so is a go client available for the rest-api? Thx!

**Comment by oktalz** [comment]
@MartijnStraatman client-native is a library that you can include directly in your app. 
If you want to have api and endpoints take a look at [dataplaneapi](https://github.com/haproxytech/dataplaneapi/) that has rest-api (and is using client-native)
