### ISSUE TITLE
Support runtime ssl commands

### ISSUE THREAD

**Issue by ViktorPegy** [haproxytech/client-native#46]
Please, add support for these commands in runtime client:
```
new ssl cert
set ssl cert
commit ssl cert
abort ssl cert
show ssl cert
del ssl cert

add ssl crt-list
del ssl crt-list
show ssl crt-list
```

**Comment by amelhusic** [comment]
Hi @ViktorPegy 
These commands are already implemented [here](https://github.com/haproxytech/client-native/commit/80cfcec3754f7fb2480c8daf35c109ee83ea6b18)

**Comment by ViktorPegy** [comment]
Cool!
