### ISSUE TITLE
runtime single client may deadlock

### ISSUE THREAD

**Issue by abstractmj** [haproxytech/client-native#68]
for runtime single client, the timeout duration in executeRaw select should not be the same with unix dial timeout duration

think about the fake code below

```golang
package main

import (
	"context"
	"fmt"
	"time"
)

const (
	taskTimeout = 5 * time.Second
)

// TaskResponse ...
type TaskResponse struct {
	result string
	err    error
}

// Task has command to execute on runtime api, and response channel for result
type Task struct {
	command  string
	response chan TaskResponse
}

// SingleRuntime handles one runtime API
type SingleRuntime struct {
	jobs chan Task
}

func (s *SingleRuntime) Init() error {
	s.jobs = make(chan Task)
	go s.handleIncommingJobs(context.Background())
	return nil
}

func (s *SingleRuntime) handleIncommingJobs(ctx context.Context) {
	for {
		select {
		case job, ok := <-s.jobs:
			if !ok {
				return
			}
			// just sleep to simulate dial timeout
			time.Sleep(taskTimeout)
			job.response <- TaskResponse{result: "result"}
		case <-ctx.Done():
			return
		}
	}
}

func (s *SingleRuntime) executeRaw(command string, retry int) (string, error) {
	response := make(chan TaskResponse)
	task := Task{
		command:  command,
		response: response,
	}
	s.jobs <- task
	select {
	case rsp := <-response:
		if rsp.err != nil && retry > 0 {
			retry--
			return s.executeRaw(command, retry)
		}
		return rsp.result, rsp.err
	case <-time.After(taskTimeout):
		return "", fmt.Errorf("timeout reached")
	}
}

func main() {
	client := &SingleRuntime{}
	if err := client.Init(); err != nil {
		fmt.Printf("init single runtime failed, err %s", err.Error())
	}
	result1, err := client.executeRaw("test command1", 1)
	if err != nil {
		fmt.Printf("executeRaw command1 failed, err %s\n", err.Error())
	} else {
		fmt.Printf("result is %s", result1)
	}

	result2, err := client.executeRaw("test command2", 1)
	if err != nil {
		fmt.Printf("executeRaw command2 failed, err %s\n", err.Error())
	} else {
		fmt.Printf("result is %s", result2)
	}
}

```

go run main.go

get deadlock

`
executeRaw command1 failed, err timeout reached
fatal error: all goroutines are asleep - deadlock!

goroutine 1 [chan send]:
main.(*SingleRuntime).executeRaw(0xc00000e028, 0x4d0689, 0xd, 0x1, 0xc000072f58, 0x1, 0x1, 0x30)
        /data/remote-vscode/tmp-bcs/test/test/main.go:58 +0x8f
main.main()
        /data/remote-vscode/tmp-bcs/test/test/main.go:83 +0x173

goroutine 6 [chan send]:
main.(*SingleRuntime).handleIncommingJobs(0xc00000e028, 0x4ec7e0, 0xc0000160a0)
        /data/remote-vscode/tmp-bcs/test/test/main.go:45 +0x90
created by main.(*SingleRuntime).Init
        /data/remote-vscode/tmp-bcs/test/test/main.go:32 +0x8c
exit status 2
`

>

**Comment by abstractmj** [comment]
Maybe we can solve this problem by setting timeout duration in executeRaw bigger or remove timeout duration in executeRaw

**Comment by abstractmj** [comment]
Execue me，Can anyone help to solve it？

**Comment by amelhusic** [comment]
Hi @abstractmj,

Thanks for reporting the issue. We are looking into it and we will notify you very soon about it.

**Comment by abstractmj** [comment]
> Hi @abstractmj,
> 
> Thanks for reporting the issue. We are looking into it and we will notify you very soon about it.

Thanks~  I'm waiting for your good news

**Comment by amelhusic** [comment]
Hi @abstractmj,

With https://github.com/haproxytech/client-native/commit/4361de9df70de6d1cf32c11f203e1b7d6bb0ead8 commit, issue should be resolved.
