### ISSUE TITLE
Server address parsing algorithm doesn't match HAProxy one in case of IPv6

### ISSUE THREAD

**Issue by daa** [haproxytech/client-native#79]
``client-native`` treats address specification without square brackets (for example ::1:8888) as one IPv6 address without port: https://github.com/haproxytech/client-native/blob/62f8396798f19dd51e463a3b3dce73cf3695a9bb/configuration/server.go#L196-L205 however HAProxy first tries to find colon or square bracket and from that extract port: https://github.com/haproxy/haproxy/blob/7530830414d5b92a31cb327201f9bc4d50a6ea64/src/tools.c#L1173-L1189
```
		/* search for : or ] whatever comes first */
		for (chr = end-1; chr > str2; chr--) {
			if (*chr == ']' || *chr == ':')
				break;
		}

		if (*chr == ':') {
			/* Found a colon before a closing-bracket, must be a port separator.
			 * This guarantee backward compatibility.
			 */
			if (!(opts & PA_O_PORT_OK)) {
				memprintf(err, "port specification not permitted here in '%s'", str);
				goto out;
			}
			*chr++ = '\0';
			port1 = chr;
		}
```
So client can't extract port from notation like ``::1:8888`` but HAProxy can work with it.

**Comment by oliwer** [comment]
Thanks for the detailed report :+1: A patch is coming soon.

**Comment by oliwer** [comment]
@mjuraga I think this can be closed with the latest version.
