### ISSUE TITLE
Support for setenv directive

### ISSUE THREAD

**Issue by cedws** [haproxytech/client-native#88]
I looked pretty hard to see if this is supported and I'm pretty sure it isn't.

[Example from HAProxy docs](https://www.haproxy.com/documentation/hapee/latest/configuration/variables/environment-variables/#set-a-new-variable-or-override-an-existing-one):

```yaml
global
   setenv PROXYNAME lb2

frontend www
   bind :80

   # Uses the overridden value, 'lb2'
   http-request add-header Via "%[req.ver] %[env(PROXYNAME)]"
```

**Comment by mjuraga** [comment]
Hi @cedws no it's not as of yet, but we are currently working on it. Should be soon, in the next release.

**Comment by oliwer** [comment]
This feature is available in the current version.
